### PR TITLE
update to v0.8.2

### PR DESCRIPTION
**Pull request by mathause**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] ~Bumped the build number (if the version is unchanged)~
* [ ] ~Reset the build number to `0` (if the version changed)~
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mathause** [comment]
@conda-forge-admin, please rerender

**Review by znicholls — APPROVED** [review]
Great

**Comment by znicholls** [comment]
Ooops @mathause I didn't see that a merge request had already been done automatically, let's hope this doesn't now cause chaos...

**Comment by mathause** [comment]
I am not sure what happens when two PRs with the same version and build number get merged. I assume conda will have safeguards in place.

#7 was automatically opened _and_ merged, I suggest we turn off the auto merging again.

**Comment by znicholls** [comment]
I was actually going to say we just leave the automerging on and try not to
forget in future haha

**Comment by mathause** [comment]
But then the PRs should not be opened automatically. In #7 it was opened at 10:04 and merged at 10:15, so we had a 11 min window to change the PR (e.g. to update dependencies). That does not work.

**Comment by znicholls** [comment]
I think the idea is that you don’t change them, if you need to you make a
new pr with a new build number

**Pull request merged**
